### PR TITLE
Fix api.d.ts

### PR DESCRIPTION
**Pull request by sjinks**
Please ensure your pull request adheres to the following guidelines:
- [x] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

#250, #252

This PR fixes two bugs introduced in #252 which break typeScript build:

```
node_modules/@adobe/helix-fetch/src/api.d.ts:214:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

214 class AbortSignal {
    ~~~~~

node_modules/@adobe/helix-fetch/src/api.d.ts:219:2 - error TS1036: Statements are not allowed in ambient contexts.

219 };
     ~


Found 2 errors.
```

The first issue was that classes need either to be `export`'ed or `declare`'d. Because `TimeoutSignal` and `AbortSignal` are exported from `src/fetch/abort.js` (and thus are externally visible), I chose to use `export`.

The second issue is that the trailing semicolon is actually an empty statement, and statements are not allowed in declaration files.

### CODE REVIEW

**Comment by mtaran** [comment]
Thanks for this fix! I tried it out locally and it does work well for me. I think `export declare class...` would be clearer than just `export class...` since as you mentioned the implementations live in other JS files. But the TypeScript compiler doesn't seem to mind, so 🤷

**Review by stefan-guggisberg — APPROVED** [review]

**Comment by stefan-guggisberg** [comment]
Thanks for the PR!
